export const JERSEYS = [
  {
    id: "home-jersey",
    name: "Mseal 25/26 Home Shirt ",
    price: 2000,
    originalPrice: 2000,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Front-Kit-for-Web_zxqu5v.png",
    rating: 4.9,
    reviews: 248,
    category: "Jersey",
    colors: ["Black", "White", "Navy"],
    discount: 24,
  },
  {
    id: "away-jersey",
    name: "Mseal 25/26 Away Shirt",
    price: 2000,
    originalPrice: 199,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Away-Front-Kit-for-Web_et0sf4.png",
    rating: 4.8,
    reviews: 192,
    category: "Jersey",
    colors: ["Blue", "Black", "Red"],
    discount: 20,
  },
  {
    id: "home-jersey-24-25",
    name: "Mseal 24/25 Home Shirt ",
    price: 1500,
    originalPrice: 249,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1762879969/WhatsApp_Image_2025-11-11_at_2.23.14_PM_kaeht9.jpg",
    rating: 4.9,
    reviews: 248,
    category: "Jersey",
    colors: ["Black", "White", "Navy"],
    discount: 24,
  },
  {
    id: "third-jersey-24-25",
    name: "Mseal 24/25 Third Shirt ",
    price: 2000,
    originalPrice: 249,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045309/img176_y5fkob.jpg",
    rating: 4.9,
    reviews: 248,
    category: "Jersey",
    colors: ["Black", "White", "Navy"],
    discount: 24,
  },
  {
    id: "blue-tracksuit",
    name: "Mseal 25/26 Blue Tracksuit",
    price: 8000,
    originalPrice: 129,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Truck-Suit-blue_aj4ucj.png",
    rating: 4.7,
    reviews: 156,
    category: "Tracksuit",
    colors: ["Gray", "Black", "Navy"],
    discount: 23,
  },
  {
    id: "blue-tracksuit-kids",
    name: "Mseal 25/26 Blue Tracksuit (Kids)",
    price: 0,
    originalPrice: 129,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Truck-Suit-blue_aj4ucj.png",
    rating: 4.7,
    reviews: 156,
    category: "Tracksuit",
    colors: ["Gray", "Black", "Navy"],
    discount: 23,
  },
  {
    id: "yellow-tracksuit",
    name: "Mseal 25/26 Yellow Tracksuit",
    price: 0,
    originalPrice: 189,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364828/Yellow-Truck-Suit_ubtycc.png",
    rating: 4.9,
    reviews: 287,
    category: "Tracksuit",
    colors: ["White", "Black", "Cream"],
    discount: 21,
  },
  {
    id: "polo",
    name: "Polo",
    price: 0,
    originalPrice: 279,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045334/img215_gi4jt9.jpg",
    rating: 4.9,
    reviews: 334,
    category: "Polo",
    colors: ["Black", "Navy", "Charcoal"],
    discount: 29,
  },
  {
    id: "bag",
    name: "Bag",
    price: 0,
    originalPrice: 169,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045309/img42_iijovz.jpg",
    rating: 4.6,
    reviews: 128,
    category: "Bag",
    colors: ["Black", "White", "Gray"],
    discount: 24,
  },
  {
    id: "pants",
    name: "3/4 Pants",
    price: 0,
    originalPrice: 159,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045280/img220_jhn4hn.jpg",
    rating: 4.8,
    reviews: 201,
    category: "Pants",
    colors: ["Beige", "Gray", "Navy"],
    discount: 25,
  },
  {
    id: "cap",
    name: "Cap",
    price: 500,
    originalPrice: 299,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045223/img101_p6s982.jpg",
    rating: 5,
    reviews: 412,
    category: "Cap",
    colors: ["Black", "Gold", "White"],
    discount: 27,
  },
  {
    id: "drawstring-bags",
    name: "Drawstring Bags",
    price: 0,
    originalPrice: 299,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045344/img51_xg5dyw.jpg",
    rating: 5,
    reviews: 412,
    category: "Bags",
    colors: ["Black", "Gold", "White"],
    discount: 27,
  },
  
]

/* eslint-disable @typescript-eslint/no-explicit-any */
export const JERSEYS_DATA: Record<string, any> = {
  "home-jersey": {
    id: "home-jersey",
    name: "Mseal 25/26 Home Shirt ",
    price: 2000,
    originalPrice: 249,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Front-Kit-for-Web_zxqu5v.png",
    additionalImages: ["https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/home-kit-back_fbhftk.png"],
    rating: 4.9,
    reviews: 248,
    category: "JERSEY",
    colors: ["Black"],
    description:
      "Experience peak athletic performance with our Elite Performance Jersey. Engineered with advanced moisture-wicking technology and premium fabric, this jersey delivers comfort and style for both professional and casual wear.",
    features: [
      "Advanced moisture-wicking technology keeps you dry",
      "Premium breathable fabric for maximum comfort",
      "Reinforced seams for durability and longevity",
      "Ergonomic fit designed for all body types",
      "UV protection to shield skin from harmful rays",
      "Machine washable for easy care",
    ],
    specifications: {
      material: "100% Performance Polyester",
      fit: "Ergonomic Athletic Cut",
      care: "Machine wash cold, tumble dry low",
      origin: "Premium Manufacturing",
      weight: "Lightweight (180gsm)",
    },
    discount: 24,
  },
    "away-jersey": {
    id: "away-jersey",
    name: "Mseal 25/26 Away Shirt",
    price: 2000,
    originalPrice: 249,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Away-Front-Kit-for-Web_et0sf4.png",
    additionalImages: [ "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364824/Awaykit-Back_jvabwc.png"],
    rating: 4.9,
    reviews: 248,
    category: "JERSEY",
    colors: ["Blue"],
    description:
      "Experience peak athletic performance with our Elite Performance Jersey. Engineered with advanced moisture-wicking technology and premium fabric, this jersey delivers comfort and style for both professional and casual wear.",
    features: [
      "Advanced moisture-wicking technology keeps you dry",
      "Premium breathable fabric for maximum comfort",
      "Reinforced seams for durability and longevity",
      "Ergonomic fit designed for all body types",
      "UV protection to shield skin from harmful rays",
      "Machine washable for easy care",
    ],
    specifications: {
      material: "100% Performance Polyester",
      fit: "Ergonomic Athletic Cut",
      care: "Machine wash cold, tumble dry low",
      origin: "Premium Manufacturing",
      weight: "Lightweight (180gsm)",
    },
    discount: 24,
  },
  "home-jersey-24-25": {
    id: "home-jersey-24-25",
    name: "Mseal 24/25 Home Shirt ",
    price: 1500,
    originalPrice: 249,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1762879969/WhatsApp_Image_2025-11-11_at_2.23.14_PM_kaeht9.jpg",
    //additionalImages: ["https://res.cloudinary.com/dfuh1q6ic/image/upload/v1762879969/WhatsApp_Image_2025-11-11_at_2.23.14_PM_kaeht9.jpg"],
    rating: 4.9,
    reviews: 248,
    category: "JERSEY",
    colors: ["Black"],
    description:
      "Experience peak athletic performance with our Elite Performance Jersey. Engineered with advanced moisture-wicking technology and premium fabric, this jersey delivers comfort and style for both professional and casual wear.",
    features: [
      "Advanced moisture-wicking technology keeps you dry",
      "Premium breathable fabric for maximum comfort",
      "Reinforced seams for durability and longevity",
      "Ergonomic fit designed for all body types",
      "UV protection to shield skin from harmful rays",
      "Machine washable for easy care",
    ],
    specifications: {
      material: "100% Performance Polyester",
      fit: "Ergonomic Athletic Cut",
      care: "Machine wash cold, tumble dry low",
      origin: "Premium Manufacturing",
      weight: "Lightweight (180gsm)",
    },
    discount: 24,
  },
  "third-jersey-24-25": {
    id: "third-jersey-24-25",
    name: "Mseal 24/25 Third Kit ",
    price: 2000,
    originalPrice: 249,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045309/img176_y5fkob.jpg",
    // additionalImages: ["https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045309/img176_y5fkob.jpg"],
    rating: 4.9,
    reviews: 248,
    category: "JERSEY",
    colors: ["Black"],
    description:
      "Experience peak athletic performance with our Elite Performance Jersey. Engineered with advanced moisture-wicking technology and premium fabric, this jersey delivers comfort and style for both professional and casual wear.",
    features: [
      "Advanced moisture-wicking technology keeps you dry",
      "Premium breathable fabric for maximum comfort",
      "Reinforced seams for durability and longevity",
      "Ergonomic fit designed for all body types",
      "UV protection to shield skin from harmful rays",
      "Machine washable for easy care",
    ],
    specifications: {
      material: "100% Performance Polyester",
      fit: "Ergonomic Athletic Cut",
      care: "Machine wash cold, tumble dry low",
      origin: "Premium Manufacturing",
      weight: "Lightweight (180gsm)",
    },
    discount: 24,
  },
  "blue-tracksuit": {
    id: "blue-tracksuit",
    name: "Mseal 25/26 Blue Tracksuit",
    price: 0,
    originalPrice: 8000,
     image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Truck-Suit-blue_aj4ucj.png",
    rating: 4.8,
    reviews: 192,
    category: "TRACKSUIT",
    colors: ["Blue"],
    description:
      "Designed for serious athletes who demand excellence. The Pro Athlete Jersey combines cutting-edge technology with sleek design to give you the competitive edge.",
    features: [
      "Professional-grade performance fabric",
      "Moisture management system",
      "Seamless construction for comfort",
      "Temperature regulation technology",
    ],
    discount: 20,
  },
  "blue-tracksuit-kids": {
    id: "blue-tracksuit-kids",
    name: "Mseal 25/26 Blue Tracksuit",
    price: 0,
    originalPrice: 199,
     image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364825/Truck-Suit-blue_aj4ucj.png",
    rating: 4.8,
    reviews: 192,
    category: "TRACKSUIT",
    colors: ["Blue"],
    description:
      "Designed for serious athletes who demand excellence. The Pro Athlete Jersey combines cutting-edge technology with sleek design to give you the competitive edge.",
    features: [
      "Professional-grade performance fabric",
      "Moisture management system",
      "Seamless construction for comfort",
      "Temperature regulation technology",
    ],
    discount: 20,
  },
    "yellow-tracksuit": {
    id: "yellow-tracksuit",
     name: "Mseal 25/26 Yellow Tracksuit",
    price: 0,
    originalPrice: 199,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760364828/Yellow-Truck-Suit_ubtycc.png",
    rating: 4.8,
    reviews: 192,
    category: "TRACKSUIT",
    colors: ["yellow"],
    description:
      "Designed for serious athletes who demand excellence. The Pro Athlete Jersey combines cutting-edge technology with sleek design to give you the competitive edge.",
    features: [
      "Professional-grade performance fabric",
      "Moisture management system",
      "Seamless construction for comfort",
      "Temperature regulation technology",
    ],
    discount: 20,
  },
  "polo": {
    id: "polo",
    name: "Polo",
    price: 0,
    originalPrice: 129,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1760029758/polo_zh8xaj.jpg",
    rating: 4.7,
    reviews: 156,
    category: "POLO",
    colors: ["White"],
    description:
      "Perfect for daily training sessions and workouts. Quality meets affordability in this reliable training jersey.",
    features: ["Durable training fabric", "Affordable premium quality", "Great for everyday athletes"],
    discount: 23,
  },
  "bag": {
    id: "bag",
    name: "Bag",
    price: 0,
    originalPrice: 189,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045309/img42_iijovz.jpg",
    rating: 4.9,
    reviews: 287,
    category: "BAG",
    colors: ["Orange"],
    description:
      "Timeless style meets modern comfort. The Heritage Classic Jersey is a wardrobe staple that never goes out of fashion.",
    features: ["Classic design that stands the test of time", "Premium comfort fabric", "Versatile color options"],
    discount: 21,
  },
  "cap": {
    id: "cap",
    name: "Cap",
    price: 500,
    originalPrice: 279,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045223/img101_p6s982.jpg",
    rating: 4.9,
    reviews: 334,
    category: "CAP",
    colors: ["Black"],
    description:
      "The future of athletic wear is here. Featuring state-of-the-art technology and innovative design, the Next-Gen Tech Jersey is built for champions.",
    features: ["State-of-the-art technology", "Advanced cooling system", "Premium durability"],
    discount: 29,
  },
  "pants": {
    id: "pants",
    name: "3/4 Pants",
    price: 0,
    originalPrice: 169,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045280/img220_jhn4hn.jpg",
    rating: 4.6,
    reviews: 128,
    category: "Casual Wear",
    colors: ["Black"],
    description:
      "Urban sophistication meets athletic performance. The Street Style Jersey is perfect for casual wear with serious style.",
    features: ["Urban design aesthetic", "Comfortable for all-day wear", "Street-style versatility"],
    discount: 24,
  },
  "drawstring-bags": {
    id: "drawstring-bags",
    name: "Drawstring Bag",
    price: 0,
    originalPrice: 299,
    image: "https://res.cloudinary.com/dfuh1q6ic/image/upload/v1758045344/img51_xg5dyw.jpg",
    rating: 5,
    reviews: 412,
    category: "BAG",
    colors: ["Blue"],
    description:
      "For champions, by champions. The Champion Series Jersey represents the pinnacle of athletic wear, combining luxury materials with uncompromising performance.",
    features: ["Premium luxury materials", "Championship-grade performance", "Exclusive design"],
    discount: 27,
  },
}
