/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    news: News;
    matches: Match;
    'payload-kv': PayloadKv;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    news: NewsSelect<false> | NewsSelect<true>;
    matches: MatchesSelect<false> | MatchesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  slug: string;
  /**
   * Paste your Cloudinary image URL here (e.g., https://res.cloudinary.com/your-cloud/image/upload/v1234567890/your-image.jpg)
   */
  cloudinaryUrl: string;
  publishDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches".
 */
export interface Match {
  id: string;
  /**
   * Auto-generated match title
   */
  matchTitle: string;
  matchDate: string;
  category: 'men' | 'women' | 'youth' | 'junior';
  homeTeam:
    | 'Ulinzi Star'
    | 'Shabana Fc'
    | 'Tusker Fc'
    | 'Gor Mahia Fc'
    | 'Mathare United'
    | 'Nairobi United'
    | 'Kariobangi Sharks'
    | 'Kenya Police Fc'
    | 'Bidco United'
    | 'Bandari Fc'
    | 'Posta Rangers Fc'
    | 'AFC Leaopards'
    | 'Sofapaka Fc'
    | 'Kakamega Homeboyz'
    | 'Mara Sugar'
    | 'KCB Fc'
    | 'Muranga Seal'
    | 'APS Bomet';
  awayTeam:
    | 'Ulinzi Star'
    | 'Shabana Fc'
    | 'Tusker Fc'
    | 'Gor Mahia Fc'
    | 'Mathare United'
    | 'Nairobi United'
    | 'Kariobangi Sharks'
    | 'Kenya Police Fc'
    | 'Bidco United'
    | 'Bandari Fc'
    | 'Posta Rangers Fc'
    | 'AFC Leaopards'
    | 'Sofapaka Fc'
    | 'Kakamega Homeboyz'
    | 'Mara Sugar'
    | 'KCB Fc'
    | 'Muranga Seal'
    | 'APS Bomet';
  /**
   * Select opponent team logo
   */
  opponentLogo?:
    | (
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910312/Ulinzi-Stars_tl47od.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910316/shabanafc_mrzcxy.jpg'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910313/Tusker-FC_eaeucx.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910297/Gor-Mahia_xc8n9c.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910325/Mathare-United_ptlpih.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910321/Nai-united_treyoj.jpg'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910292/Kariobangi-Sharks_zjgvxd.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910292/Police_qyg86z.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910298/Bidco-FC-Logo_odxoos.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910298/Bandari_wcacwy.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910318/Posta-Rangers_bc9rvb.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910308/AFC-Leopards_t6rhsj.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910314/sofapaka_ltzbb8.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910293/Kakamega-Homeboyz-1_m0wtw0.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910292/marasugar_jivabw.jpg'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910292/KCB_pi1pfg.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910321/muranga-seal_trzy7m.png'
        | 'https://res.cloudinary.com/dfuh1q6ic/image/upload/v1759910299/OIP-1_qngv38.jpg'
      )
    | null;
  venue: string;
  /**
   * Ticket purchase link (only for home games)
   */
  ticketUrl?: string | null;
  status?: ('upcoming' | 'live' | 'finished' | 'postponed' | 'cancelled') | null;
  score?: {
    homeScore?: number | null;
    awayScore?: number | null;
  };
  competition: 'premier-league' | 'fkf-cup' | 'super-cup' | 'friendly';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'matches';
        value: string | Match;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  slug?: T;
  cloudinaryUrl?: T;
  publishDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "matches_select".
 */
export interface MatchesSelect<T extends boolean = true> {
  matchTitle?: T;
  matchDate?: T;
  category?: T;
  homeTeam?: T;
  awayTeam?: T;
  opponentLogo?: T;
  venue?: T;
  ticketUrl?: T;
  status?: T;
  score?:
    | T
    | {
        homeScore?: T;
        awayScore?: T;
      };
  competition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}